version: "0.2"
import:
  - "@cspell/dict-en_us/cspell-ext.json"
dictionaries:
  - en_us
languageId: "*"
words:
  - esbenp
allowCompoundWords: true
useGitignore: true
files:
  - "**"
enableFiletypes:
  - "*"
