on:
  pull_request: {}

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "24.4.1"
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v4
      - run: just build-all ${{ github.sha }}
