on:
  push: {}
  pull-request: {}

jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "24.4.1"
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v4
      - run: just test-all
